name: deploy vue
on:
  push:
    branches:
      - prod
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: build the code
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: Debug SSH Configuration
        run: |
          echo "Current SSH key:"
          echo "${{ secrets.SSH_KEY }}" | head -c 100
          echo "..."
          echo "SSH username: ${{ secrets.SSH_USER_NAME }}"
          echo "Target host: ${{ secrets.PROD_HOST }}"

      - name: Check SSH Connectivity
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "SSH connection successful!"
            whoami
            hostname -I

      - name: set the ubuntu user as the owner of the /var/www/html directory for ubuntu 24+
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R ubuntu /var/www/html

      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./dist/*"
          target: "/var/www/html"
          strip_components: 1

      - name: set the root user back as the owner of the /var/www/html directory for ubuntu 24+
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R root /var/www/html
